### ISSUE TITLE
SEO Meta Tag

### ISSUE THREAD

**Issue by AdeboyeDN** [PipeOpsHQ/pipeops-documentation#1]
Update the meta tag to PipeOps default description 
![image](https://user-images.githubusercontent.com/65312338/215746504-15107bbd-7257-42e1-b455-03d2f6b0c2dc.png)

**Comment by kaf-lamed-beyt** [comment]
Hi 👋, can you assign this to me?  

I'm guessing the new description in the og attribute will replace "Nextra: the next docs builder", yeah?

If yes, what's the description that I'd replace it with? Do you mind sharing it with me? 

[Edit]: I think I found it already. This is it 👇🏼 , right? 

> Official documentation for PipeOps a No-code Tool for Cloud Deployments & Infrastructure Management.

**Comment by AdeboyeDN** [comment]
Yes, that's the description.

**Comment by kaf-lamed-beyt** [comment]
Awesome, thanks!

**Comment by kaf-lamed-beyt** [comment]
In the theme config here 👇🏼, the meta description has already been provided. But, I'm a little bit confused on why it is not rendered in the title. 

https://github.com/PipeOpsHQ/pipeops-documentation/blob/2f979844822d729204ffc12d969765c124b726c5/theme.config.tsx#L18-L28

I also noticed that it uses the `frontMatter` key. Would I need to add a YAML frontmatter syntax in index.mdx? something like this? 👇🏼 

```mdx
---
frontMatter: "description"
---
```

**Comment by AdeboyeDN** [comment]
Hi take a look at [here](https://nextra.site/docs/docs-theme/theme-configuration#dynamic-tags-based-on-page) to learn more about the frontMatter tag

**Comment by AdeboyeDN** [comment]
Hi @kaf-lamed-beyt,

The issue has been resolved, thank you for your contribution you can also try PipeOps out and give us your review.

Best,
Daniel.

**Comment by kaf-lamed-beyt** [comment]
Alright, will do! 🤞🏽
