### ISSUE TITLE
Light Theme Logo

### ISSUE THREAD

**Issue by AdeboyeDN** [PipeOpsHQ/pipeops-documentation#2]
Fix the light theme logo
![image](https://user-images.githubusercontent.com/65312338/215746803-bcbd4988-2387-4a30-89e3-83fa9b72e096.png)

**Comment by kaf-lamed-beyt** [comment]
Can you assign this to me?

What exactly is wrong with the logo? Do we need to replace it with another variant? Say for example, there's logo for light and dark mode?

cc: @AdeboyeDN

**Comment by AdeboyeDN** [comment]
[Logo Files.zip](https://github.com/PipeOpsHQ/pipeops-documentation/files/10558532/Logo.Files.zip)

Yes there's a logo for light and dark mode

**Comment by kaf-lamed-beyt** [comment]
Great! I'll get started, and ping you when I'm done.
